## 03 - Data Anonymization

### Objective

This notebook prepares the extracted datasets for ethical analysis by removing personally identifiable information (PII).

Before generating anonymous student identifiers, the student records from the three academic terms are compared to verify that they represent the same cohort. This validation ensures that a single, consistent Student_ID can be assigned to each student and used across all datasets throughout the project.

The anonymized datasets produced in this notebook will be used for all subsequent data cleaning, analysis, SQL integration, and Power BI reporting.

In [1]:
import pandas as pd

### Loading the Student Datasets

The Student datasets extracted from the three academic term workbooks are loaded for comparison.

In [2]:
term1_students = pd.read_csv("../data/interim/term1/term1_student.csv")

term2_students = pd.read_csv("../data/interim/term2/term2_student.csv")

term3_students = pd.read_csv("../data/interim/term3/term3_student.csv")

### Inspecting the Student Datasets

The structure of each dataset is reviewed to confirm that the expected variables are available before comparing the student records.

In [3]:
print("Term 1")
display(term1_students.head())

print("Term 2")
display(term2_students.head())

print("Term 3")
display(term3_students.head())

Term 1

  STUDENT ID       STUDENT NAME
0       4056   AGBENOR  ALFRED
1        567     AGBENU JORDAN
2        749        AGBO PRINCE
3       2050  AGBOTSE EBENEZER
4        696   APPIAH EMMANUEL

Term 2

  STUDENT ID       STUDENT NAME
0       4056   AGBENOR  ALFRED
1        567     AGBENU JORDAN
2        749        AGBO PRINCE
3       2050  AGBOTSE EBENEZER
4        696   APPIAH EMMANUEL

Term 3

  STUDENT ID       STUDENT NAME
0       4056   AGBENOR  ALFRED
1        567     AGBENU JORDAN
2        749        AGBO PRINCE
3       2050  AGBOTSE EBENEZER
4        696   APPIAH EMMANUEL

## Comparing the Number of Student Records

The number of student records in each academic term is compared to identify any differences in cohort size.

In [4]:
comparison = pd.DataFrame({
    "Term": ["Term 1", "Term 2", "Term 3"],
    "Students": [
        len(term1_students),
        len(term2_students),
        len(term3_students)
    ]
})

comparison

     Term  Students
0  Term 1        59
1  Term 2        58
2  Term 3        54

In [5]:
# Select only the columns required for comparison

term1_compare = term1_students[["STUDENT ID", "STUDENT NAME"]].copy()

term2_compare = term2_students[["STUDENT ID", "STUDENT NAME"]].copy()

term3_compare = term3_students[["STUDENT ID", "STUDENT NAME"]].copy()

In [6]:
for df in [term1_compare, term2_compare, term3_compare]:

    df["STUDENT NAME"] = (
        df["STUDENT NAME"]
        .str.strip()
        .str.upper()
    )

In [7]:
term1_vs_term2 = term1_compare.merge(
    term2_compare,
    on=["STUDENT ID", "STUDENT NAME"],
    how="outer",
    indicator=True
)

term1_vs_term2

   STUDENT ID                  STUDENT NAME      _merge
0         140                  TETTEH MAVIS        both
1         160                  GAMOR ESTHER        both
2        2050              AGBOTSE EBENEZER        both
3        2325             ASHANGBOR ABIGAIL        both
4         267                 OFFEI JUSTICE        both
5         269                BONNEY CHARITY        both
6         270                 DJABA BELINDA        both
7         271                   ESHUN EVANS        both
8         272                 ASIGBEY JOYCE        both
9         300               GOMASHIE PRINCE        both
10        309                 SEIDU IBRAHIM        both
11        318              ESSEL EMMANUELLA        both
12        320                ASAMOAH STELLA        both
13        339                 YEBOAH OLIVIA        both
14        365            AGBENYEFIA BRIDGET        both
15        385                   BAWA BASSIT        both
16        385               HABLEAME SHILLA        both
17        387             ADOMAKO PRISCILLA        both
18        388              OKYERE PRISCILLA        both
19       4056               AGBENOR  ALFRED        both
20       4062                  BAAH COMFORT        both
21       4063                  GAMAH ANGELA        both
22       4065                  TWUMASI VERA        both
23       4070              ACQUAH PRISCILLA        both
24       4240                ASIAMAH JOSEPH        both
25        432                 APPIAH GLADYS        both
26        433         NKETIA POKUAA CECELIA        both
27        435                ASARE RICHMOND        both
28        436                   OWUSU RUBEN        both
29        437                ENTSIE FRANCIS        both
30        437                SALIFU ZULAIHA        both
31        445              AKATAYURE REGINA        both
32        459              OTU KOFI SOLOMON        both
33        503                   OSEI BELVIS        both
34        508                MENSAH VANESSA        both
35        511                   AMOAH SAFOA        both
36        514                 DIXON HARRIET        both
37        554             AGBEMAZI PRECIOUS        both
38        567                 AGBENU JORDAN        both
39        593                 ODOI MARGARET        both
40        616                WORMENOR JULIA        both
41        624                      ADI ROSE        both
42        643                ATTIPOE EUNICE        both
43        645                TAGBOR MICHAEL        both
44        670                 BOATENG AGNES        both
45        696               APPIAH EMMANUEL        both
46        698           ANIM AMOAH NHYIRABA        both
47        709             SEFA AMA OWUSUWAA        both
48        714                 DEDIHA GIDEON        both
49        727            AWUAH HEHELI JERRY   left_only
50        727            AWUAH KEKELI JERRY  right_only
51       7315                GYEMENA SERWAH        both
52       7334               ENCHILL KENNETH        both
53        744  OCQUAYE ANGELINA NAA SHORMEY   left_only
54        749                   AGBO PRINCE        both
55        768             BRAHENE PRISCILLA        both
56       A070               NUMEGBOR WISDOM        both
57       A071                 AKROFI DORCAS        both
58       A244               MENSAH FLORENCE        both
59       A319                DANQWAH PHILIP        both

In [8]:
term1_vs_term2[
    term1_vs_term2["_merge"] != "both"
]

   STUDENT ID                  STUDENT NAME      _merge
49        727            AWUAH HEHELI JERRY   left_only
50        727            AWUAH KEKELI JERRY  right_only
53        744  OCQUAYE ANGELINA NAA SHORMEY   left_only

In [9]:
term1_vs_term3 = term1_compare.merge(
    term3_compare,
    on=["STUDENT ID", "STUDENT NAME"],
    how="outer",
    indicator=True
)

term1_vs_term3[
    term1_vs_term3["_merge"] != "both"
]

   STUDENT ID                  STUDENT NAME      _merge
5         269                BONNEY CHARITY   left_only
14        365            AGBENYEFIA BRIDGET   left_only
34        508                MENSAH VANESSA   left_only
49        727            AWUAH HEHELI JERRY   left_only
50        727            AWUAH KEKELI JERRY  right_only
53        744  OCQUAYE ANGELINA NAA SHORMEY   left_only
55        768             BRAHENE PRISCILLA   left_only

In [10]:
term2_vs_term3 = term2_compare.merge(
    term3_compare,
    on=["STUDENT ID", "STUDENT NAME"],
    how="outer",
    indicator=True
)

term2_vs_term3[
    term2_vs_term3["_merge"] != "both"
]

   STUDENT ID        STUDENT NAME     _merge
5         269      BONNEY CHARITY  left_only
14        365  AGBENYEFIA BRIDGET  left_only
34        508      MENSAH VANESSA  left_only
53        768   BRAHENE PRISCILLA  left_only

### Investigating Student Record Differences

The comparison identified differences between the student records across the three academic terms.

These differences may reflect changes in enrollment, such as withdrawals, or new admissions. Alternatively, they may indicate inconsistencies in data entry.

The unmatched records will be reviewed before generating the master student list.

## Creating a Master Student List

The student records from all three academic terms are combined into a single master list.

This ensures that every student who appeared during the academic year is represented before anonymization.

In [11]:
master_students = pd.concat(
    [
        term1_compare,
        term2_compare,
        term3_compare
    ],
    ignore_index=True
)

master_students.head()

  STUDENT ID      STUDENT NAME
0       4056   AGBENOR  ALFRED
1        567     AGBENU JORDAN
2        749       AGBO PRINCE
3       2050  AGBOTSE EBENEZER
4        696   APPIAH EMMANUEL

In [12]:
master_students = (
    master_students
    .drop_duplicates(subset="STUDENT ID")
    .sort_values("STUDENT ID")
    .reset_index(drop=True)
)

master_students

   STUDENT ID                  STUDENT NAME
0         140                  TETTEH MAVIS
1         160                  GAMOR ESTHER
2        2050              AGBOTSE EBENEZER
3        2325             ASHANGBOR ABIGAIL
4         267                 OFFEI JUSTICE
5         269                BONNEY CHARITY
6         270                 DJABA BELINDA
7         271                   ESHUN EVANS
8         272                 ASIGBEY JOYCE
9         300               GOMASHIE PRINCE
10        309                 SEIDU IBRAHIM
11        318              ESSEL EMMANUELLA
12        320                ASAMOAH STELLA
13        339                 YEBOAH OLIVIA
14        365            AGBENYEFIA BRIDGET
15        385                   BAWA BASSIT
16        387             ADOMAKO PRISCILLA
17        388              OKYERE PRISCILLA
18       4056               AGBENOR  ALFRED
19       4062                  BAAH COMFORT
20       4063                  GAMAH ANGELA
21       4065                  TWUMASI VERA
22       4070              ACQUAH PRISCILLA
23       4240                ASIAMAH JOSEPH
24        432                 APPIAH GLADYS
25        433         NKETIA POKUAA CECELIA
26        435                ASARE RICHMOND
27        436                   OWUSU RUBEN
28        437                ENTSIE FRANCIS
29        445              AKATAYURE REGINA
30        459              OTU KOFI SOLOMON
31        503                   OSEI BELVIS
32        508                MENSAH VANESSA
33        511                   AMOAH SAFOA
34        514                 DIXON HARRIET
35        554             AGBEMAZI PRECIOUS
36        567                 AGBENU JORDAN
37        593                 ODOI MARGARET
38        616                WORMENOR JULIA
39        624                      ADI ROSE
40        643                ATTIPOE EUNICE
41        645                TAGBOR MICHAEL
42        670                 BOATENG AGNES
43        696               APPIAH EMMANUEL
44        698           ANIM AMOAH NHYIRABA
45        709             SEFA AMA OWUSUWAA
46        714                 DEDIHA GIDEON
47        727            AWUAH HEHELI JERRY
48       7315                GYEMENA SERWAH
49       7334               ENCHILL KENNETH
50        744  OCQUAYE ANGELINA NAA SHORMEY
51        749                   AGBO PRINCE
52        768             BRAHENE PRISCILLA
53       A070               NUMEGBOR WISDOM
54       A071                 AKROFI DORCAS
55       A244               MENSAH FLORENCE
56       A319                DANQWAH PHILIP

In [13]:
print("Total unique students:", len(master_students))

Total unique students: 57

In [14]:
master_students = (
    master_students
    .sort_values("STUDENT ID")
    .reset_index(drop=True)
)

master_students["Student_ID"] = [
    f"ST{str(i).zfill(4)}"
    for i in range(1, len(master_students) + 1)
]

In [15]:
# Master students with anonymized IDs
master_students["Student_ID"] = [
    f"ST{str(i).zfill(4)}"
    for i in range(1, len(master_students) + 1)
]

master_students

   STUDENT ID                  STUDENT NAME Student_ID
0         140                  TETTEH MAVIS     ST0001
1         160                  GAMOR ESTHER     ST0002
2        2050              AGBOTSE EBENEZER     ST0003
3        2325             ASHANGBOR ABIGAIL     ST0004
4         267                 OFFEI JUSTICE     ST0005
5         269                BONNEY CHARITY     ST0006
6         270                 DJABA BELINDA     ST0007
7         271                   ESHUN EVANS     ST0008
8         272                 ASIGBEY JOYCE     ST0009
9         300               GOMASHIE PRINCE     ST0010
10        309                 SEIDU IBRAHIM     ST0011
11        318              ESSEL EMMANUELLA     ST0012
12        320                ASAMOAH STELLA     ST0013
13        339                 YEBOAH OLIVIA     ST0014
14        365            AGBENYEFIA BRIDGET     ST0015
15        385                   BAWA BASSIT     ST0016
16        387             ADOMAKO PRISCILLA     ST0017
17        388              OKYERE PRISCILLA     ST0018
18       4056               AGBENOR  ALFRED     ST0019
19       4062                  BAAH COMFORT     ST0020
20       4063                  GAMAH ANGELA     ST0021
21       4065                  TWUMASI VERA     ST0022
22       4070              ACQUAH PRISCILLA     ST0023
23       4240                ASIAMAH JOSEPH     ST0024
24        432                 APPIAH GLADYS     ST0025
25        433         NKETIA POKUAA CECELIA     ST0026
26        435                ASARE RICHMOND     ST0027
27        436                   OWUSU RUBEN     ST0028
28        437                ENTSIE FRANCIS     ST0029
29        445              AKATAYURE REGINA     ST0030
30        459              OTU KOFI SOLOMON     ST0031
31        503                   OSEI BELVIS     ST0032
32        508                MENSAH VANESSA     ST0033
33        511                   AMOAH SAFOA     ST0034
34        514                 DIXON HARRIET     ST0035
35        554             AGBEMAZI PRECIOUS     ST0036
36        567                 AGBENU JORDAN     ST0037
37        593                 ODOI MARGARET     ST0038
38        616                WORMENOR JULIA     ST0039
39        624                      ADI ROSE     ST0040
40        643                ATTIPOE EUNICE     ST0041
41        645                TAGBOR MICHAEL     ST0042
42        670                 BOATENG AGNES     ST0043
43        696               APPIAH EMMANUEL     ST0044
44        698           ANIM AMOAH NHYIRABA     ST0045
45        709             SEFA AMA OWUSUWAA     ST0046
46        714                 DEDIHA GIDEON     ST0047
47        727            AWUAH HEHELI JERRY     ST0048
48       7315                GYEMENA SERWAH     ST0049
49       7334               ENCHILL KENNETH     ST0050
50        744  OCQUAYE ANGELINA NAA SHORMEY     ST0051
51        749                   AGBO PRINCE     ST0052
52        768             BRAHENE PRISCILLA     ST0053
53       A070               NUMEGBOR WISDOM     ST0054
54       A071                 AKROFI DORCAS     ST0055
55       A244               MENSAH FLORENCE     ST0056
56       A319                DANQWAH PHILIP     ST0057

In [16]:
# Save the master student list to a CSV file
master_students.to_csv(
    "../data/metadata/student_lookup.csv",
    index=False
)

### Loading the Student Lookup Table

The student lookup table contains the mapping between the original school-assigned student identifiers and the anonymous Student_ID values thats was generated for this project.

This lookup table will be used to anonymize all extracted datasets while maintaining consistent relationships across the academic terms.

In [24]:
student_lookup = pd.read_csv("../data/metadata/student_lookup.csv")

student_lookup.head()

  STUDENT ID       STUDENT NAME Student_ID
0        140       TETTEH MAVIS     ST0001
1        160       GAMOR ESTHER     ST0002
2       2050   AGBOTSE EBENEZER     ST0003
3       2325  ASHANGBOR ABIGAIL     ST0004
4        267      OFFEI JUSTICE     ST0005

### Creating a Reusable Anonymization Function

A reusable function is created to anonymize datasets containing student information.

The function performs the following tasks:

- Loads the dataset.
- Matches each student using the school-assigned STUDENT ID.
- Appends the anonymous Student_ID.
- Removes personally identifiable information.
- Saves the anonymized dataset for subsequent processing.

In [42]:
def anonymize_dataset(df, lookup):

    if "STUDENT ID" in df.columns:

        anonymized = df.merge(
            lookup[["STUDENT ID", "Student_ID"]],
            on="STUDENT ID",
            how="left"
        )

    elif "STUDENT NAME" in df.columns:

        anonymized = df.merge(
            lookup[["STUDENT NAME", "Student_ID"]],
            on="STUDENT NAME",
            how="left"
        )

    elif "NAME" in df.columns:

        lookup_name = lookup.rename(
            columns={"STUDENT NAME": "NAME"}
        )

        anonymized = df.merge(
            lookup_name[["NAME", "Student_ID"]],
            on="NAME",
            how="left"
        )

    else:

        raise ValueError("No student identifier found.")

    anonymized.insert(
        0,
        "Student_ID",
        anonymized.pop("Student_ID")
    )

    return anonymized

## Testing the Anonymization Function

The Attendance dataset is used to verify that the anonymization function correctly assigns Student_ID values before removing identifying information.

In [26]:
attendance = pd.read_csv("../data/interim/term1/term1_attendance.csv")

attendance.head()

                NAME  Attendance
0   AGBENOR  ALFRED         69.0
1     AGBENU JORDAN         63.0
2        AGBO PRINCE        55.0
3  AGBOTSE EBENEZER         69.0
4   APPIAH EMMANUEL         54.0

In [39]:
attendance.columns.tolist()

['NAME', 'Attendance']

In [40]:
datasets = {
    "Student": term1_students,
    "Attendance": pd.read_csv("../data/interim/term1/term1_attendance.csv"),
    "Test 1": pd.read_csv("../data/interim/term1/term1_test_1.csv"),
    "Test 2": pd.read_csv("../data/interim/term1/term1_test_2.csv"),
    "Group Work": pd.read_csv("../data/interim/term1/term1_group_work.csv"),
    "Project Work": pd.read_csv("../data/interim/term1/term1_project_work.csv"),
    "Class Score": pd.read_csv("../data/interim/term1/term1_classscore.csv"),
    "Exam Score": pd.read_csv("../data/interim/term1/term1_examscore.csv"),
    "General Remarks": pd.read_csv("../data/interim/term1/term1_general_remarks.csv")
}

In [52]:
# Clean names in the attendance dataset
attendance["NAME"] = (
    attendance["NAME"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Clean names in the lookup table
student_lookup["STUDENT NAME"] = (
    student_lookup["STUDENT NAME"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [54]:
attendance["NAME"] = (
    attendance["NAME"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

student_lookup["STUDENT NAME"] = (
    student_lookup["STUDENT NAME"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

In [56]:
attendance_anonymized = attendance.merge(
    student_lookup.rename(columns={"STUDENT NAME": "NAME"})[
        ["NAME", "Student_ID"]
    ],
    on="NAME",
    how="left"
)

attendance_anonymized.head(56)

                            NAME  Attendance Student_ID
0                 AGBENOR ALFRED        69.0     ST0019
1                  AGBENU JORDAN        63.0     ST0037
2                    AGBO PRINCE        55.0     ST0052
3               AGBOTSE EBENEZER        69.0     ST0003
4                APPIAH EMMANUEL        54.0     ST0044
5                 ASARE RICHMOND        54.0     ST0027
6                 ASIAMAH JOSEPH        65.0     ST0024
7             AWUAH HEHELI JERRY        69.0     ST0048
8                    BAWA BASSIT        69.0     ST0016
9                 DANQWAH PHILIP        69.0     ST0057
10                 DEDIHA GIDEON        60.0     ST0047
11               ENCHILL KENNETH        68.0     ST0050
12                ENTSIE FRANCIS        65.0     ST0029
13                   ESHUN EVANS        67.0     ST0008
14               GOMASHIE PRINCE        67.0     ST0010
15               NUMEGBOR WISDOM        64.0     ST0054
16                 OFFEI JUSTICE        69.0     ST0005
17                   OSEI BELVIS        66.0     ST0032
18              OTU KOFI SOLOMON        67.0     ST0031
19                   OWUSU RUBEN        62.0     ST0028
20                 SEIDU IBRAHIM        67.0     ST0011
21                TAGBOR MICHAEL        55.0     ST0042
22              ACQUAH PRISCILLA        69.0     ST0023
23                      ADI ROSE        69.0     ST0040
24             ADOMAKO PRISCILLA        69.0     ST0017
25             AGBEMAZI PRECIOUS        62.0     ST0036
26            AGBENYEFIA BRIDGET        63.0     ST0015
27              AKATAYURE REGINA        68.0     ST0030
28                 AKROFI DORCAS        67.0     ST0055
29                   AMOAH SAFOA        67.0     ST0034
30           ANIM AMOAH NHYIRABA        67.0     ST0045
31                 APPIAH GLADYS        63.0     ST0025
32                ASAMOAH STELLA        65.0     ST0013
33             ASHANGBOR ABIGAIL        69.0     ST0004
34                 ASIGBEY JOYCE        68.0     ST0009
35                ATTIPOE EUNICE        58.0     ST0041
36                  BAAH COMFORT        52.0     ST0020
37                 BOATENG AGNES        69.0     ST0043
38                BONNEY CHARITY        67.0     ST0006
39                 DIXON HARRIET        67.0     ST0035
40                 DJABA BELINDA        69.0     ST0007
41              ESSEL EMMANUELLA        68.0     ST0012
42                  GAMAH ANGELA        69.0     ST0021
43                  GAMOR ESTHER        68.0     ST0002
44                GYEMENA SERWAH        69.0     ST0049
45               HABLEAME SHILLA        64.0        NaN
46               MENSAH FLORENCE        63.0     ST0056
47                MENSAH VANESSA        68.0     ST0033
48         NKETIA POKUAA CECELIA        66.0     ST0026
49  OCQUAYE ANGELINA NAA SHORMEY         NaN     ST0051
50                 ODOI MARGARET        68.0     ST0038
51              OKYERE PRISCILLA        68.0     ST0018
52                SALIFU ZULAIHA        69.0        NaN
53             SEFA AMA OWUSUWAA        67.0     ST0046
54                  TETTEH MAVIS        69.0     ST0001
55                  TWUMASI VERA        67.0     ST0022

In [69]:
master_students = pd.concat(
    [
        term1_students[["STUDENT ID", "STUDENT NAME"]],
        term2_students[["STUDENT ID", "STUDENT NAME"]],
        term3_students[["STUDENT ID", "STUDENT NAME"]]
    ],
    ignore_index=True
)

master_students = (
    master_students
    .drop_duplicates(subset="STUDENT ID", keep="first")
    .reset_index(drop=True)
)

master_students.head()

  STUDENT ID       STUDENT NAME
0       4056   AGBENOR  ALFRED
1        567     AGBENU JORDAN
2        749        AGBO PRINCE
3       2050  AGBOTSE EBENEZER
4        696   APPIAH EMMANUEL

In [73]:
master_students = pd.concat(
    [
        term1_students[["STUDENT ID", "STUDENT NAME"]],
        term2_students[["STUDENT ID", "STUDENT NAME"]],
        term3_students[["STUDENT ID", "STUDENT NAME"]]
    ],
    ignore_index=True
)

print(master_students.shape)

(171, 2)

In [74]:
master_students[
    master_students["STUDENT NAME"].str.contains(
        "SALIFU|HABLEAME",
        case=False,
        na=False
    )
]

    STUDENT ID       STUDENT NAME
45         385  HABLEAME SHILLA
52         437   SALIFU ZULAIHA
104        385  HABLEAME SHILLA
110        437   SALIFU ZULAIHA
160        385  HABLEAME SHILLA
165        437   SALIFU ZULAIHA